
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name:  FastAPI Middleware docker build push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# permissions:
#   contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: run tests
      run:  python3 -m pytest app.py
    
    - name: Build docker image for FastAPI
      run : docker build -t '${{secrets.DOCKER_USERNAME}}'/fastapi-middleware:'${{github.sha}}' .
    
    
    - name: Logging to the Docker hub
      run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'
    - name: push image to docker hub
      run: docker push '${{secrets.DOCKER_USERNAME}}'/fastapi-middleware:'${{github.sha}}' 
    # - name: run server
    #   run: docker run --detach 'fastapi-middleware'
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
    # Specify connection via URL (replaces server_address, server_port, secure,
    # username and password)
    #
    # Format:
    #
    #  * smtp://user:password@server:port
        #  * smtp+starttls://user:password@server:port
        connection_url: ${{secrets.MAIL_CONNECTION}}
        # Required mail server address if not connection_url:
        server_address: smtp.gmail.com
        # Server port, default 25:
        server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional (recommended) mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: ronmkare1@gmail.com.com,yaganron@gmail.com
        # Required sender full name (address can be skipped):
        from: ronmkare@gmail.com # <user@example.com>
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
  debug:
    name: Check failure
    needs: build
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
    # Specify connection via URL (replaces server_address, server_port, secure,
    # username and password)
    #
    # Format:
    #
        #  * smtp://user:password@server:port
            #  * smtp+starttls://user:password@server:port
            connection_url: ${{secrets.MAIL_CONNECTION}}
            # Required mail server address if not connection_url:
            server_address: smtp.gmail.com
            # Server port, default 25:
            server_port: 465
            # Optional whether this connection use TLS (default is true if server_port is 465)
            secure: true
            # Optional (recommended) mail server username:
            username: ${{secrets.MAIL_USERNAME}}
            # Optional (recommended) mail server password:
            password: ${{secrets.MAIL_PASSWORD}}
            # Required mail subject:
            subject: Github Actions job result
            # Required recipients' addresses:
            to: ronmkare1@gmail.com.com,yaganron@gmail.com
            # Required sender full name (address can be skipped):
            from: ronmkare@gmail.com # <user@example.com>
            # Optional plain body:
            body: Build job of ${{github.repository}} FAILED TO COMPLETE!!!